Dev/v1.2
hms-networks/sc-flexy-datapoint-lib pull request #15
Opened 2021-06-25 15:05 UTC by alexjhawk

2021-06-25 15:09 UTC, oliver-walker-hms submitted a review, later dismissed

2021-06-25 18:34 UTC, TomKimsey requested changes
It would be beneficial to have more class documentation for DataPointIntegerEnum. Maybe even giving an example or reason for why to use it. Also the class name seems a bit confusing. Isnt the meaningful value datatype really a string and not an int?

ex
0 = "Off"
1= "On, Not Running"
2 = "On, Running"
3 = "On, Not Running, Faulted"

To me string better defines those datatypes than integer. Of maybe the class should be something more like DataPointIntegerEncodedString

Edit: Encoded is probably not the right word to use 
Maybe DataPointIntegerMappedString

2021-06-25 18:54 UTC, alexjhawk commented
> It would be beneficial to have more class documentation for DataPointIntegerEnum. Maybe even giving an example or reason for why to use it. Also the class name seems a bit confusing. Isnt the meaningful value datatype really a string and not an int?
> 
> ex
> 0 = "Off"
> 1= "On, Not Running"
> 2 = "On, Running"
> 3 = "On, Not Running, Faulted"
> 
> To me string better defines those datatypes than integer. Of maybe the class should be something more like DataPointIntegerEncodedString
> 
> Edit: Encoded is probably not the right word to use
> Maybe DataPointIntegerMappedString

- Renamed new data point class to your suggested name "DataPointIntegerMappedString" because I feel that fits well. 
- Added example in class documentation

2021-06-25 20:43 UTC, TomKimsey requested changes

2021-06-25 20:43 UTC, TomKimsey commented on CHANGELOG.md
> +- Added integer enumeration data point type
needs to get updated for new class name

2021-06-25 20:46 UTC, alexjhawk commented on CHANGELOG.md
> +- Added integer enumeration data point type
updated

2021-06-28 12:05 UTC, TomKimsey approved these changes

2021-06-28 12:12 UTC, oliver-walker-hms approved these changes

2021-06-28 12:13 UTC, merged